name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - name: Checking your code format
        run: csbt scalafmtCheckAll
      - name: Run tests
        run: csbt headerCheck test demo/fastLinkJS
